import React from "react";

export const languages = {
    ["PICK-ONE"]:{},
  Albanian: { image: "sql", text: "sq" },
  Arabic: { image: "ara", text: "ar" },
  ["Chinese-simplified"]: { image: "chi_sim", text: "zh-Hans" },
  English: { image: "eng", text: "en" },
  French: { image: "fra", text: "fr" },
  German: { image: "deu", text: "de" },
  Hebrew: { image: "heb", text: "he" },
  Hindi: { image: "hin", text: "hi" },
  Hungarian: { image: "hun", text: "hu" },
  Indonesian: { image: "ind", text: "id" },
  Irish: { image: "gle", text: "ga" },
  Italian: { image: "ita", text: "it" },
  Japanese: { image: "jpn", text: "ja" },
  Korean: { image: "kor", text: "ko" },
  Norwegian: { image: "nor", text: "nb" },
  Polish: { image: "pol", text: "pl" },
  Portuguese: { image: "por", text: "pt-pt" },
  Russian: { image: "rus", text: "ru" },
  Spanish: { image: "dpa", text: "es" },
  Swedish: { image: "swe", text: "sv" },
  Thai: { image: "tha", text: "th" },
  Turkish: { image: "tur", text: "tr" },
  Ukrainian: { image: "ukr", text: "uk" },
  Vietnamese: { image: "vie", text: "vi" },
};
